# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryScriptNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('type', models.PositiveSmallIntegerField()),
                ('args', models.CharField(default=b'', max_length=200)),
                ('user', models.CharField(max_length=40)),
                ('index', models.PositiveIntegerField()),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('total_time', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['index'],
                'db_table': 'history_script_node',
            },
        ),
        migrations.CreateModel(
            name='HistoryScriptServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('log', models.TextField(default=b'')),
                ('code', models.IntegerField(null=True)),
                ('total_time', models.PositiveIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.HistoryScriptNode')),
            ],
            options={
                'db_table': 'history_script_server',
            },
        ),
        migrations.CreateModel(
            name='HistoryStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('index', models.PositiveIntegerField()),
                ('type', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['index'],
                'db_table': 'history_step',
            },
        ),
        migrations.CreateModel(
            name='HistoryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=40)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('total_time', models.PositiveIntegerField(default=0)),
                ('project_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'history_task',
            },
        ),
        migrations.AddField(
            model_name='historystep',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.HistoryTask'),
        ),
        migrations.AddField(
            model_name='historyscriptnode',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.HistoryStep'),
        ),
    ]
