# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyscriptserver',
            old_name='name',
            new_name='host',
        ),
        migrations.AddField(
            model_name='historyscriptnode',
            name='order',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historyscriptnode',
            name='content',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='historyscriptserver',
            name='log',
            field=models.BinaryField(),
        ),
    ]
