# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('type', models.IntegerField()),
                ('create_user', models.CharField(max_length=40)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_user', models.CharField(max_length=40)),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('project_id', models.IntegerField()),
            ],
            options={
                'db_table': 'script',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('create_user', models.CharField(max_length=40)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
