# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='content',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
