# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='project',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
